module.exports = {
  words: [
    'Arya Stark',
    'Khaleesi',
    'Crow',
    'Whitewalkers'
    'Jaime Lannister',
    'Cersei Lannister',
    'Ned Stark',
    'Catelyn Stark',
    'Daenerys Targaryen',
    'Jorah Mormont',
    'Petyr Baeilish',
    'Littlefinger',
    'Viserys Targaryen',
    'Jon Snow',
    'Sansa Stark',
    'Robb Stark',
    'Theon Greyjoy',
    "Reek",
    'Bran Stark',
    'Three Eyed Raven',
    'Joffrey Baratheon',
    'Sandor Clegane',
    'The Hound',
    'Gregor Clegane',
    'The Mountain',
    'Tyrion Lannister',
    'The Imp',
    'Khal Drogo',
    'Davos Seaworth',
    'Samwell Tarly',
    'Margaery Tyrell',
    'Stannis Baratheon',
    'Melisandre',
    'Jeor Mormont',
    'Bronn',
    'Varys',
    'Shae',
    'Tywin Lannister',
    'Ygritte',
    'Gendry',
    'Tormund Giantsbane',
    'Gilly',
    'Brienne of Tarth',
    'Ramsay Bolton',
    'Ellaria Sand',
    'Daario Naharis',
    'Missandei',
    'Tommen Baratheon',
    'Roose Bolton',
    'The High Sparrow',
    'Grand Maester Pycelle',
    'Hodor',
    'Osha',
    'Rickon Stark',
    'Lancel Lannister',
    'Myrcella Baratheon',
    'Maester Aemon',
    'Alliser Thorne',
    'Loras Tyrell',
    'Hot Pie',
    'Podrick Payne',
    'Yara Greyjoy',
    'Grey Worm',
    'Olenna Tyrell',
    'Shireen Baratheon',
    'Meera Reed',
    'Jojen Reed',
    'Olly',
    'The Waif',
    'Robin Arryn',
    'Rinley Baratheon',
    'Beric Dondarrion',
    'Walder Frey',
    'The Nights Watch',
    'The Wall',
    'Lysa Arryn',
    'Syrio Forel',
    'Jon Arryn',
    'Craster',
    'Balon Greyjoy',
    'Edmure Tully',
    'The Black Fish',
    'Lyanna Mormont',
    'Aerys Targaryen',
    'The Mad King',
    'The Night King',
    'Wun Weg Wun Dar Wun',
    'The Sand Snakes',
    'Oberyn Martell',
    'Grey Wind',
    'Lady',
    'Nymeria',
    'Summer',
    'Shaggydog',
    'Ghost',
    'Direwolves',
    'House Lannister',
    'House Tyrell',
    'House Stark',
    'House Tully',
    'House Arryn',
    'House Baratheon',
    'House Martell',
    'Kings Landing',
    'Braavos',
    'Dorne',
    'Westeros',
    'Volantis',
    'Winterfell',
    'High Garden',
    'The Iron Bank',
    'The Red Wedding',
    'The Battle of the Bastards',
    'The Battle of the Blackwater',
    'Dragonglass',
    'Valyrian Steel',
    'Longclaw',
    'Astapor',
    'Harrenhal',
    'The Red Keep',
    'Crasters Keep',
    'Meereen',
    'Dragonstone',
    'Riverrun',
    'Casterly Rock',
    'Yunkai',
    'Drogon',
    'Rhaegal',
    'Viserion',
    'Dothraki',
    'Stormborn',
    'Mother of Dragons',
    'Breaker of Chains',
    'The Masters',
    'Maester',
    'Milk of the Poppy',
    'Greyscale',
    'Raven',
    'The Second Sons',
    'The Seven',
    'The Unsullied',
    'Warg',
    'Wildfire',
    'Wildling',
    'The Old Gods',
    'The Lord of Light',
    'The Many Faced God'
  ]
}
